CREATE TABLE picture (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data bytea,
    picture_content_type varchar
);

CREATE TABLE resume_pdf (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_data_pdf bytea
);

CREATE TABLE person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL UNIQUE,
    password varchar NOT NULL,
    first_name varchar(40) NOT NULL,
    last_name varchar(40) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    phone varchar(20) NOT NULL UNIQUE,
    location varchar(200) NOT NULL,
    created_at TIMESTAMP,
    role varchar(100) NOT NULL,
    about_me varchar(1000),
    picture_id int,
    resume_pdf_id int,
    FOREIGN KEY (picture_id) REFERENCES picture(id),
    FOREIGN KEY (resume_pdf_id) REFERENCES resume_pdf(id)
);

INSERT INTO person(username, password, first_name, last_name, email, phone, location, created_at, role) VALUES ('admin', '$2a$10$vT9IS4rZbjXZaahqozB5Te5wbZx.tcnxaw/bufj7iBLjCkzgv4Ie6',
        'admin', 'admin', 'admin@test.com', '123456789', 'Earth', localtimestamp, 'ROLE_ADMIN');

CREATE TABLE qualification (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    degree varchar(255) NOT NULL,
    university varchar(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    person_id int,
    FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE skill (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name varchar(255) NOT NULL,
    experience int NOT NULL,
    person_id int,
    FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE work_experience (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name varchar(255) NOT NULL,
    position varchar(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    person_id int,
    FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE offer_category (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category varchar(255) NOT NULL,
    description varchar(1000)
);

INSERT INTO offer_category(category, description) VALUES ('Software Developer', 'Middle');
INSERT INTO offer_category(category, description) VALUES ('Backend Developer', 'Junior');
INSERT INTO offer_category(category, description) VALUES ('Frontend Developer', 'Senior');
INSERT INTO offer_category(category, description) VALUES ('Full-stack Developer', 'Junior / Middle');

CREATE TABLE offer (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    description varchar(1000) NOT NULL,
    company_name varchar(255) NOT NULL,
    required_skills varchar,
    min_salary int CHECK ( min_salary >= 0 ),
    max_salary int CHECK ( max_salary >= 0 ),
    min_experience_years int CHECK ( max_salary >= 0 ),
    max_experience_years int CHECK ( max_salary >= 0 ),
    location varchar(255),
    offer_type varchar(255),
    offer_category_id int,
    FOREIGN KEY (offer_category_id) REFERENCES offer_category(id) ON DELETE CASCADE,
    posted_at TIMESTAMP,
    application_count int DEFAULT 0,
    employer_id int,
    company_logo_id int,
    resume_pdf_id int,
    FOREIGN KEY (employer_id) REFERENCES person(id),
    FOREIGN KEY (company_logo_id) REFERENCES picture(id),
    FOREIGN KEY (resume_pdf_id) REFERENCES resume_pdf(id)
);

CREATE TABLE application (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int,
    FOREIGN KEY (person_id) REFERENCES person(id),
    offer_id int,
    FOREIGN KEY (offer_id) REFERENCES offer(id) ON DELETE CASCADE,
    application_date TIMESTAMP,
    status varchar(255),
    resume_pdf_id int,
    FOREIGN KEY (resume_pdf_id) REFERENCES resume_pdf(id)
);

DROP TABLE IF EXISTS work_experience;
DROP TABLE IF EXISTS skill;
DROP TABLE IF EXISTS qualification;
DROP TABLE IF EXISTS application;
DROP TABLE IF EXISTS offer;
DROP TABLE IF EXISTS offer_category;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS picture;
DROP TABLE IF EXISTS resume_pdf;
